# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Api.Health do
  @moduledoc """
  API calls for all endpoints tagged `Health`.
  """

  alias Flagr.Connection
  import Flagr.RequestBuilder


  @doc """
  Check if Flagr is healthy

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Flagr.Model.Health{}} on success
  {:error, info} on failure
  """
  @spec get_health(Tesla.Env.client, keyword()) :: {:ok, Flagr.Model.Health.t} | {:error, Tesla.Env.t}
  def get_health(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/health")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Flagr.Model.Health{})
  end
end
