# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Api.Segment do
  @moduledoc """
  API calls for all endpoints tagged `Segment`.
  """

  alias Flagr.Connection
  import Flagr.RequestBuilder


  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag to get
  - body (CreateSegmentRequest): create a segment under a flag
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Flagr.Model.Segment{}} on success
  {:error, info} on failure
  """
  @spec create_segment(Tesla.Env.client, integer(), Flagr.Model.CreateSegmentRequest.t, keyword()) :: {:ok, Flagr.Model.Segment.t} | {:error, Tesla.Env.t}
  def create_segment(connection, flag_id, body, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/flags/#{flag_id}/segments")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Flagr.Model.Segment{})
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - segment_id (integer()): numeric ID of the segment
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec delete_segment(Tesla.Env.client, integer(), integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_segment(connection, flag_id, segment_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/flags/#{flag_id}/segments/#{segment_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag to get
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, [%Segment{}, ...]} on success
  {:error, info} on failure
  """
  @spec find_segments(Tesla.Env.client, integer(), keyword()) :: {:ok, list(Flagr.Model.Segment.t)} | {:error, Tesla.Env.t}
  def find_segments(connection, flag_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/flags/#{flag_id}/segments")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode([%Flagr.Model.Segment{}])
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - segment_id (integer()): numeric ID of the segment
  - body (PutSegmentRequest): update a segment
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Flagr.Model.Segment{}} on success
  {:error, info} on failure
  """
  @spec put_segment(Tesla.Env.client, integer(), integer(), Flagr.Model.PutSegmentRequest.t, keyword()) :: {:ok, Flagr.Model.Segment.t} | {:error, Tesla.Env.t}
  def put_segment(connection, flag_id, segment_id, body, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/flags/#{flag_id}/segments/#{segment_id}")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Flagr.Model.Segment{})
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - body (PutSegmentReorderRequest): reorder segments
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec put_segments_reorder(Tesla.Env.client, integer(), Flagr.Model.PutSegmentReorderRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def put_segments_reorder(connection, flag_id, body, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/flags/#{flag_id}/segments/reorder")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end
end
