# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Api.Variant do
  @moduledoc """
  API calls for all endpoints tagged `Variant`.
  """

  alias Flagr.Connection
  import Flagr.RequestBuilder


  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - body (CreateVariantRequest): create a variant
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Flagr.Model.Variant{}} on success
  {:error, info} on failure
  """
  @spec create_variant(Tesla.Env.client, integer(), Flagr.Model.CreateVariantRequest.t, keyword()) :: {:ok, Flagr.Model.Variant.t} | {:error, Tesla.Env.t}
  def create_variant(connection, flag_id, body, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/flags/#{flag_id}/variants")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Flagr.Model.Variant{})
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - variant_id (integer()): numeric ID of the variant
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec delete_variant(Tesla.Env.client, integer(), integer(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def delete_variant(connection, flag_id, variant_id, _opts \\ []) do
    %{}
    |> method(:delete)
    |> url("/flags/#{flag_id}/variants/#{variant_id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, [%Variant{}, ...]} on success
  {:error, info} on failure
  """
  @spec find_variants(Tesla.Env.client, integer(), keyword()) :: {:ok, list(Flagr.Model.Variant.t)} | {:error, Tesla.Env.t}
  def find_variants(connection, flag_id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/flags/#{flag_id}/variants")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode([%Flagr.Model.Variant{}])
  end

  @doc """

  ## Parameters

  - connection (Flagr.Connection): Connection to server
  - flag_id (integer()): numeric ID of the flag
  - variant_id (integer()): numeric ID of the variant
  - body (PutVariantRequest): update a variant
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Flagr.Model.Variant{}} on success
  {:error, info} on failure
  """
  @spec put_variant(Tesla.Env.client, integer(), integer(), Flagr.Model.PutVariantRequest.t, keyword()) :: {:ok, Flagr.Model.Variant.t} | {:error, Tesla.Env.t}
  def put_variant(connection, flag_id, variant_id, body, _opts \\ []) do
    %{}
    |> method(:put)
    |> url("/flags/#{flag_id}/variants/#{variant_id}")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Flagr.Model.Variant{})
  end
end
