# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.CreateSegmentRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"rolloutPercent"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"rolloutPercent" => integer()
  }
end

defimpl Poison.Decoder, for: Flagr.Model.CreateSegmentRequest do
  def decode(value, _options) do
    value
  end
end

