# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.CreateFlagRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"key",
    :"template"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"key" => String.t,
    :"template" => String.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.CreateFlagRequest do
  def decode(value, _options) do
    value
  end
end

