# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.Distribution do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"percent",
    :"variantKey",
    :"variantID"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"percent" => integer(),
    :"variantKey" => String.t,
    :"variantID" => integer()
  }
end

defimpl Poison.Decoder, for: Flagr.Model.Distribution do
  def decode(value, _options) do
    value
  end
end

