# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.Flag do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"key",
    :"description",
    :"enabled",
    :"tags",
    :"segments",
    :"variants",
    :"dataRecordsEnabled",
    :"entityType",
    :"notes",
    :"createdBy",
    :"updatedBy",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"key" => String.t,
    :"description" => String.t,
    :"enabled" => boolean(),
    :"tags" => [Tag],
    :"segments" => [Segment],
    :"variants" => [Variant],
    :"dataRecordsEnabled" => boolean(),
    :"entityType" => String.t,
    :"notes" => String.t,
    :"createdBy" => String.t,
    :"updatedBy" => String.t,
    :"updatedAt" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.Flag do
  import Flagr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tags", :list, Flagr.Model.Tag, options)
    |> deserialize(:"segments", :list, Flagr.Model.Segment, options)
    |> deserialize(:"variants", :list, Flagr.Model.Variant, options)
  end
end

