# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.FlagSnapshot do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"updatedBy",
    :"flag",
    :"updatedAt"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"updatedBy" => String.t,
    :"flag" => Flag,
    :"updatedAt" => String.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.FlagSnapshot do
  import Flagr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"flag", :struct, Flagr.Model.Flag, options)
  end
end

