# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.PutSegmentReorderRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"segmentIDs"
  ]

  @type t :: %__MODULE__{
    :"segmentIDs" => [integer()]
  }
end

defimpl Poison.Decoder, for: Flagr.Model.PutSegmentReorderRequest do
  def decode(value, _options) do
    value
  end
end

