# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.PutFlagRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"description",
    :"dataRecordsEnabled",
    :"entityType",
    :"enabled",
    :"key",
    :"notes"
  ]

  @type t :: %__MODULE__{
    :"description" => String.t,
    :"dataRecordsEnabled" => boolean(),
    :"entityType" => String.t,
    :"enabled" => boolean(),
    :"key" => String.t,
    :"notes" => String.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.PutFlagRequest do
  def decode(value, _options) do
    value
  end
end

