# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.PutDistributionsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"distributions"
  ]

  @type t :: %__MODULE__{
    :"distributions" => [Distribution]
  }
end

defimpl Poison.Decoder, for: Flagr.Model.PutDistributionsRequest do
  import Flagr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"distributions", :list, Flagr.Model.Distribution, options)
  end
end

