# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.SegmentDebugLog do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"segmentID",
    :"msg"
  ]

  @type t :: %__MODULE__{
    :"segmentID" => integer(),
    :"msg" => String.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.SegmentDebugLog do
  def decode(value, _options) do
    value
  end
end

