# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.SetFlagEnabledRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"enabled"
  ]

  @type t :: %__MODULE__{
    :"enabled" => boolean()
  }
end

defimpl Poison.Decoder, for: Flagr.Model.SetFlagEnabledRequest do
  def decode(value, _options) do
    value
  end
end

