# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.Tag do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: Flagr.Model.Tag do
  def decode(value, _options) do
    value
  end
end

