# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Flagr.Model.Variant do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"key",
    :"attachment"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"key" => String.t,
    :"attachment" => Object
  }
end

defimpl Poison.Decoder, for: Flagr.Model.Variant do
  import Flagr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"attachment", :struct, Flagr.Model.Object, options)
  end
end

